// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCObwHhkLhlxgmFKyKQF7bFxtcq93HDEKk',
    appId: '1:631760167388:ios:5b1639a6a7b4f4e3fa6f19',
    messagingSenderId: '631760167388',
    projectId: 'study8-88277',
    storageBucket: 'study8-88277.appspot.com',
    iosClientId: '631760167388-g7ei0t4dntqd9eo3d4d1iqoggcodi1an.apps.googleusercontent.com',
    iosBundleId: 'com.example.study8',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgy1GNMUk9hVmRx5YCZhLXNQQYSwepNlQ',
    appId: '1:631760167388:web:05f6618894a6af92fa6f19',
    messagingSenderId: '631760167388',
    projectId: 'study8-88277',
    authDomain: 'study8-88277.firebaseapp.com',
    storageBucket: 'study8-88277.appspot.com',
    measurementId: 'G-FGB1JFBDT3',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCObwHhkLhlxgmFKyKQF7bFxtcq93HDEKk',
    appId: '1:631760167388:ios:5b1639a6a7b4f4e3fa6f19',
    messagingSenderId: '631760167388',
    projectId: 'study8-88277',
    storageBucket: 'study8-88277.appspot.com',
    iosClientId: '631760167388-g7ei0t4dntqd9eo3d4d1iqoggcodi1an.apps.googleusercontent.com',
    iosBundleId: 'com.example.study8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpxO09XZDlFC7GSOxnDLLpFAUuIqWDuqc',
    appId: '1:631760167388:android:8a9c050fca9bd103fa6f19',
    messagingSenderId: '631760167388',
    projectId: 'study8-88277',
    storageBucket: 'study8-88277.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgy1GNMUk9hVmRx5YCZhLXNQQYSwepNlQ',
    appId: '1:631760167388:web:ae2a3b783206542ffa6f19',
    messagingSenderId: '631760167388',
    projectId: 'study8-88277',
    authDomain: 'study8-88277.firebaseapp.com',
    storageBucket: 'study8-88277.appspot.com',
    measurementId: 'G-J09L4Y9CGL',
  );

}